Add support for retrieving user certificates
mguessan/davmail pull request #353
Opened 2024-05-13 19:09 UTC by singe

It's possible to add a public S/MIME certificate for a user to the GAL. These are used when a user wants to encrypt a mail to another user, or validate their signature. The public certificate of the recipient is required. Being able to look them up rather than engage in a manual or offline synchornisation process makes this easier, as well as fetching updated certificates when they're changed.

The bulk of this work was done by @krutelp in
https://github.com/mguessan/davmail/pull/98 I merely extended it to support the UserSMIMECertificate field in addition to the MSExchangeCertificate field.

These are both part of the EWS Contact:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.contact?view=exchange-ews-api

I tried to do it without using ContactDataShape.AllProperties but like @krutelp couldn't find a method that would return the certificates.

I extended the ignored tags based on what was returned by our Microsoft365 instance, but not all of the fields listed under the Contact type above.

I slightly modified the original PR to use Dos line endings in ResolveNamesMethod.java so exact changes could be observed instead of the entire file being changed.

I also added the keys to the contact in ExchangeSession.java as KEY1 and KEY2.

Finally, I undid the small changes in LdapConnection.java to the isMatch() methods to have them take an ExchangeSession.Contact and put them back to Map<String, String>. This was mostly done to limit the changes in the patch to those necessary.

2024-05-16 05:25 UTC, esabol requested changes

2024-05-16 05:25 UTC, esabol commented on src/java/davmail/exchange/ews/ResolveNamesMethod.java
> +                            certificate = value;
Yes, I agree. @singe , could you make that change please?

2024-05-20 20:24 UTC, singe commented on src/java/davmail/exchange/ews/ResolveNamesMethod.java
> +                            certificate = value;
Done and thank you.

2024-05-20 20:51 UTC, esabol approved these changes

2024-05-22 07:24 UTC, singe commented
@mguessan anything else you'd like to see in this?

2024-06-19 15:05 UTC, mguessan commented
@singe looks good, need some time to validate.

Previous attempt broke thing on synchronisation.

2024-10-16 12:11 UTC, dirkhusemann commented
Any chance of this PR making it into the release? I'm currently stumbling over this as well.

2025-02-03 13:35 UTC, mguessan commented
Patch merged in trunk, can you please confirm it's working as expected ?

2025-02-03 17:04 UTC, esabol commented
> Patch merged in trunk, can you please confirm it's working as expected ?

@mguessan : When you merged, you apparently forgot to include the second commit in this PR?

That resulted in this issue:

https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&id=mguessan_davmail&open=AZTH52i_ilSScCEmP6nb

The second commit in the PR added a `firstValueRead = true;`, but I suggest considering eliminating `firstValueRead` entirely and just use `certificate.isEmpty()` for the condition.

2025-02-16 15:52 UTC, mguessan commented
Merged as is, you are right we may simplify the code a bit.

Closing PR

2025-02-16 15:52 UTC, closed without merging